
# Directories -----------------------------------------------------------------
motif_dir: # Directory with motif PWMs
metadata_dir: # Directory with metadata
dnase_data_dir: # Directory with DNase data
chip_data_dir: # Directory with ChIP data
ref_genome_dir: # Directory with reference genome
blacklist_dir:  # Directory with ENCODE blacklist
out_dir: # Directory with processed data
log_dir: # Directory with the log files

# Global settings -------------------------------------------------------------
data_type: 'Duke'
thresh_pvalue: '1e-5'
ver_genome: 'hg38'
bin: 'M5'
motif_set: 'JASPAR'
chip_ref_size: '2e7'
dnase_ref_size: '1e8'
