#! /usr/bin/env Rscript

# R script to normalize, bin DNase (or ATAC) data with MILLIPEDE binning scheme and
# transform (asinh or log2) DNase (or ATAC) counts
library(optparse)
library(TOP)

# Process the command-line arguments.
option_list <- list(
  make_option("--dnase_counts", action="store", default=NULL, type='character',
              help="Filename of DNase-seq count rds."),
  make_option("--idxstats", action="store", default=NULL, type='character',
              help="The DNase-seq idxstats file generated by samtools."),
  make_option("--bin", action="store", default='M5', type='character',
              help="MILLIPEDE binning scheme."),
  make_option("--ref_size", action="store", default=1e8, type='integer',
              help="Reference library size for DNase-seq."),
  make_option("--transform", action="store", default='asinh', type='character',
              help="Transformation of binned DNase counts (asinh or log2)."),
  make_option('--outdir', action='store', default=NULL, type='character',
              help='Output directory.'),
  make_option('--outname', action='store', default=NULL, type='character',
              help='Output filename prefix.')
)

opt <- parse_args(OptionParser(option_list=option_list))
dnase_counts_file    <- opt$dnase_counts
file_idxstats        <- opt$idxstats
bin_method           <- opt$bin
ref_size             <- opt$ref_size
transform            <- opt$transform
outdir               <- opt$outdir
outname              <- opt$outname


dnase_normalized_counts_file <- file.path(outdir, paste0(outname, '.normalized_countmatrix.rds'))
dnase_bins_file <- file.path(outdir, paste0(outname, '.', bin_method, '_bins.rds'))

if( !file.exists(dnase_counts_file) ){
  cat(paste(dnase_counts_file, 'file does not exist.
            Probably no candidate sites were found.\n'))

}else{
  # Normalize, binning and transform DNase counts to DNase bins
  dnase_counts <- readRDS(dnase_counts_file)
  dnase_countmatrix <- as.matrix(dnase_counts$combined[,-c(1:4)])

  normalized_dnase_countmatrix <- normalize_dnase(dnase_countmatrix, file_idxstats, ref_size)
  dnase_bins <- bin_dnase(normalized_dnase_countmatrix, bin_method, transform)

  normalized_dnase_countmatrix.df <- cbind(dnase_counts$combined[,1:4], normalized_dnase_countmatrix)
  saveRDS(normalized_dnase_countmatrix.df, dnase_normalized_counts_file)

  dnase_bins.df <- cbind(dnase_counts$combined[,1:4], dnase_bins)
  saveRDS(dnase_bins.df, dnase_bins_file)

}
