
#' @title Binning and transform DNase count matrix
#'
#' @description Binning DNase using MILLIPEDE binning and
#' then take asinh (or log2) transform
#' @param dnase_counts DNase (or ATAC) count matrix
#' @param bin.method MILLIPEDE binning scheme (Default: 'M5').
#' @param transform asinh or log2 transform of DNase counts
#'
#' @export
#'
bin_dnase <- function(dnase_counts,
                      bin.method=c('M5','M1','M2','M3','M12','M24'),
                      transform=c('asinh','log2')) {

  bin.method <- match.arg(bin.method)
  transform <- match.arg(transform)

  ## MILLIPEDE binning DNase counts
  cat('Binning DNase data with MILLIPEDE', bin.method, 'binning... \n')
  dnase_bins.df <- as.data.frame(millipede_binning(dnase_counts)[[bin.method]])

  if (transform == 'asinh') {
    cat('Perform asinh transform. \n')
    dnase_bins.df <- asinh(dnase_bins.df)
  } else if (transform == 'log2') {
    cat('Perform log2 transform. \n')
    dnase_bins.df <- log2(dnase_bins.df+1)
  }

  return(dnase_bins.df)

}



#' @title Count DNase cuts with different MILLIPEDE binning settings.
#'
#' @param data DNase data matrix, rows are candidate sites,
#' columns are DNase cuts with 100bp flanks around motifs in forward and reverse strands
#' @param combine_strands Method to combine DNase cuts from M24 bins in both strands to M12 bins:
#' 'vertical' (default) or 'motif'.
#' @export
#'
millipede_binning <- function(data, combine_strands=c('vertical', 'motif')) {

  combine_strands <- match.arg(combine_strands)

  flank_LF1 <- 81:100
  flank_LF2 <- flank_LF1 - 20
  flank_LF3 <- flank_LF2 - 20
  flank_LF4 <- flank_LF3 - 20
  flank_LF5 <- flank_LF4 - 20
  flank_RF1 <- (ncol(data)/2-99): (ncol(data)/2-80)
  flank_RF2 <- flank_RF1 + 20
  flank_RF3 <- flank_RF2 + 20
  flank_RF4 <- flank_RF3 + 20
  flank_RF5 <- flank_RF4 + 20

  flank_LR1 <- ncol(data)/2 + flank_LF1
  flank_LR2 <- ncol(data)/2 + flank_LF2
  flank_LR3 <- ncol(data)/2 + flank_LF3
  flank_LR4 <- ncol(data)/2 + flank_LF4
  flank_LR5 <- ncol(data)/2 + flank_LF5
  flank_RR1 <- ncol(data)/2 + flank_RF1
  flank_RR2 <- ncol(data)/2 + flank_RF2
  flank_RR3 <- ncol(data)/2 + flank_RF3
  flank_RR4 <- ncol(data)/2 + flank_RF4
  flank_RR5 <- ncol(data)/2 + flank_RF5

  motif_LF <- 101: round(ncol(data)/4)
  motif_RF <- (round(ncol(data)/4)+1) : (ncol(data)/2-100)
  motif_LR <- ncol(data)/2 + motif_LF
  motif_RR <- ncol(data)/2 + motif_RF

  M24 <- data.frame(
    flank_LF5 <- rowSums(data[,flank_LF5]),
    flank_LF4 <- rowSums(data[,flank_LF4]),
    flank_LF3 <- rowSums(data[,flank_LF3]),
    flank_LF2 <- rowSums(data[,flank_LF2]),
    flank_LF1 <- rowSums(data[,flank_LF1]),

    motif_LF <- rowSums(data[,motif_LF]),
    motif_RF <- rowSums(data[,motif_RF]),

    flank_RF1 <- rowSums(data[,flank_RF1]),
    flank_RF2 <- rowSums(data[,flank_RF2]),
    flank_RF3 <- rowSums(data[,flank_RF3]),
    flank_RF4 <- rowSums(data[,flank_RF4]),
    flank_RF5 <- rowSums(data[,flank_RF5]),

    flank_LR5 <- rowSums(data[,flank_LR5]),
    flank_LR4 <- rowSums(data[,flank_LR4]),
    flank_LR3 <- rowSums(data[,flank_LR3]),
    flank_LR2 <- rowSums(data[,flank_LR2]),
    flank_LR1 <- rowSums(data[,flank_LR1]),

    motif_LR <- rowSums(data[,motif_LR]),
    motif_RR <- rowSums(data[,motif_RR]),

    flank_RR1 <- rowSums(data[,flank_RR1]),
    flank_RR2 <- rowSums(data[,flank_RR2]),
    flank_RR3 <- rowSums(data[,flank_RR3]),
    flank_RR4 <- rowSums(data[,flank_RR4]),
    flank_RR5 <- rowSums(data[,flank_RR5]))

  if(combine_strands == 'vertical'){
    # vertical combine
    M12 <- M24[,c(1:12)] + M24[,c(13:24)]
  }else if (combine_strands == 'motif') {
    M12 <- M24[,c(1:12)] + M24[,c(24:13)]
  } else {
    stop('combine_strands needs to be vertical(default) or motif!')
  }

  colnames(M12) <- c('L5', 'L4', 'L3', 'L2', 'L1', 'motif_L', 'motif_R', 'R1', 'R2', 'R3', 'R4', 'R5')

  left2_sum <- rowSums(M12[,c(1,2)])
  left1_sum <- rowSums(M12[,c(3,4,5)])
  motif_sum <- rowSums(M12[,c(6,7)])
  right1_sum <- rowSums(M12[,c(8,9,10)])
  right2_sum <- rowSums(M12[,c(11,12)])

  M5 <- data.frame(left2_sum, left1_sum, motif_sum, right1_sum, right2_sum)

  M3 <- data.frame(left1_sum, motif_sum, right1_sum)

  M2 <- data.frame(left1_sum, right1_sum)

  M1 <- data.frame(left1_right1_sum = left1_sum + right1_sum)

  res <- list(M24 = M24,
              M12 = M12,
              M5 = M5,
              M3 = M3,
              M2 = M2,
              M1 = M1)

  return(res)

}


#' @title Normalize DNase counts
#'
#' @description Normalize DNase counts by library size scaling,
#' bin DNase using MILLIPEDE binning and then take log2 or asinh transform
#' @param dnase_counts DNase count matrix
#' @param idxstats_file The idxstats file generated by samtools
#' @param ref.size Scale to DNase-seq reference library size (Default: 100 million)
#'
#' @export
#'
normalize_dnase <- function(dnase_counts,
                            idxstats_file,
                            ref.size=1e8) {

  ## Count total mapped reads (chr1:22)
  total_readsMapped <- get_total_reads(idxstats_file, select.chr = TRUE)

  ## Normalize (scale) read counts
  cat('Normalize (scale) to', ref.size / 1e6, 'million reads. \n')
  scaling_factor <- ref.size / total_readsMapped
  normalized_dnase_counts <- dnase_counts * scaling_factor

  return(normalized_dnase_counts)

}


#' @title Normalize, binning and transform DNase counts
#'
#' @description Normalize DNase counts by library size,
#' binning DNase using MILLIPEDE binning and then take asinh or log2 transform
#'
#' @param dnase_counts DNase count matrix
#' @param idxstats_file The idxstats file generated by samtools
#' @param ref.size Scale to DNase-seq reference library size (Default: 100 million)
#' @param bin.method MILLIPEDE binning scheme (Default: 'M5').
#' @param transform asinh or log2 transform of DNase counts.
#'
#' @export
#'
normalize_bin_dnase <- function(dnase_counts,
                                idxstats_file,
                                ref.size=1e8,
                                bin.method=c('M5','M1','M2','M3','M12','M24'),
                                transform=c('asinh','log2')) {

  bin.method <- match.arg(bin.method)
  transform <- match.arg(transform)

  ## Count total mapped reads (chr1:22)
  total_readsMapped <- get_total_reads(idxstats_file, select.chr = TRUE)

  ## Normalize (scale) read counts
  cat('Normalize (scale) to', ref.size / 1e6, 'million reads. \n')
  scaling_factor <- ref.size / total_readsMapped
  normalized_dnase_counts <- dnase_counts * scaling_factor

  ## MILLIPEDE binning DNase counts
  cat('Binning DNase data with MILLIPEDE', bin.method, 'binning... \n')
  dnase_bins.df <- as.data.frame(millipede_binning(normalized_dnase_counts)[[bin.method]])

  if (transform == 'asinh') {
    cat('Perform asinh transform. \n')
    dnase_bins.df <- asinh(dnase_bins.df)
  } else if (transform == 'log2') {
    cat('Perform log2 transform. \n')
    dnase_bins.df <- log2(dnase_bins.df+1)
  }

  return(dnase_bins.df)

}


#' @title Merge DNase counts, then normalize merged DNase counts data.
#' @description Merge DNase counts, then normalize DNase counts by library size scaling.
#' @param dnase_counts_files DNase counts files
#' @param dnase_idxstats_files The DNase idxstats files generated by samtools
#' @param ref.size Scale to DNase-seq reference library size (Default: 100 million for DNase-seq)
#'
#' @export
#'
merge_normalize_dnase_counts <- function(dnase_counts_files, dnase_idxstats_files, ref.size = 1e8){

  ## Load raw counts and sum over the replicates
  for (i in 1:length(dnase_counts_files)) {
    dnase_counts <- readRDS(dnase_counts_files[i])$combined
    dnase_countmatrix <- as.matrix(dnase_counts[,-c(1:4)])
    if ( i == 1 ) {
      sites_info <- dnase_counts[,1:4]
      dnase_total_countmatrix <- dnase_countmatrix
    }else{
      dnase_total_countmatrix <- dnase_total_countmatrix + dnase_countmatrix
    }
  }

  ## Count total mapped reads (chr1:22)
  total_readsMapped <- sum(sapply(dnase_idxstats_files, get_total_reads, select.chr = TRUE))

  ## Normalize (scale) read counts
  cat('Normalize (scale) to', ref.size / 1e6, 'million reads. \n')
  scaling_factor <- ref.size / total_readsMapped
  normalized_dnase_countmatrix <- dnase_total_countmatrix * scaling_factor

  normalized_dnase_countmatrix.df <- cbind(sites_info, normalized_dnase_countmatrix)

  return(normalized_dnase_countmatrix.df)

}


#' @title Count DNase-seq or ATAC-seq cleavage for a given genome.
#'
#' @param bam_file Sorted BAM file.
#' @param chrom_size_file File name of genome sizes by chromosomes.
#' @param outdir Output directory.
#' @param outname Output prefix.
#' @param bedtools_path Path to bedtools executable.
#' @param bedGraphToBigWig_path Path to UCSC bedGraphToBigWig executable.
#' @param bedSort_path Path to UCSC bedSort executable.
#' @export
#'
count_dnase_genome_cuts <- function(bam_file,
                                    chrom_size_file,
                                    outdir,
                                    outname,
                                    bedtools_path='bedtools',
                                    bedGraphToBigWig_path='bedGraphToBigWig',
                                    bedSort_path='bedSort') {

  # Checking input arguments
  if ( Sys.which(bedtools_path) == "") {
    stop( 'bedtools could not be executed, set bedtools_path. \n' )
  }

  if ( Sys.which(bedGraphToBigWig_path) == "" ) {
    stop( 'bedGraphToBigWig could not be executed, set bedGraphToBigWig_path.\n' )
  }

  if ( Sys.which(bedSort_path) == "" ) {
    stop( 'bedSort could not be executed, set bedSort_path.\n' )
  }

  dir.create(outdir, showWarnings = F, recursive = T)

  for (strand in c('+', '-')) {
    if (strand == '+') {
      out_file <- file.path(outdir, paste0(outname, '.fwd.genomecounts.bw'))
    } else if (strand == '-') {
      out_file <- file.path(outdir, paste0(outname, '.rev.genomecounts.bw'))
    }

    cat('Counting genome cleavage for', bam_file, 'in', strand, 'strand...\n')
    temp_file <- paste0(tools::file_path_sans_ext(out_file), '.bedGraph')
    cmd <- paste(bedtools_path, 'genomecov -bg -5', '-strand', strand,
                 '-ibam', bam_file, '>', temp_file)
    system(cmd)

    # sort .bedGraph file
    cat('Sorting bedGraph ...\n')
    cmd <- paste(bedSort_path, temp_file, temp_file)
    system(cmd)

    # Convert bedGraph to Bigwig format
    cat('Converting bedGraph to Bigwig format ...\n')
    cmd <- paste(bedGraphToBigWig_path, temp_file, chrom_size_file, out_file)
    system(cmd)

    file.remove(temp_file)
  }

}

#' @title Get DNase count matrices for candidate sites.
#'
#' @param sites_file Filename for candidate sites
#' @param dnase_fwd_count_file Filename for DNase counts in forward strand (Bigwig format)
#' @param dnase_rev_count_file Filename for DNase counts in reverse strand (Bigwig format)
#' @param dnase_fwd_matrix_file Filename for DNase count matrix in forward strand
#' @param dnase_rev_matrix_file Filename for DNase count matrix in reverse strand
#' @param bwtool_path Path to bwtool executable.
#' @export
#'
get_dnase_sites_counts <- function(sites_file,
                                   dnase_fwd_count_file, dnase_rev_count_file,
                                   dnase_fwd_matrix_file, dnase_rev_matrix_file,
                                   bwtool_path='bwtool') {

  options(scipen=999) # not to use scientific notation when writing out

  if ( Sys.which(bwtool_path) == '' ) {
    stop( 'bwtool could not be executed, set bwtool_path!' )
  }

  dir.create(dirname(dnase_fwd_matrix_file), showWarnings = F, recursive = T)

  cat('Matching DNase count matrices around candidate sites ... \n')
  cmd <- paste('cut -f 1-4', sites_file, '|', bwtool_path, 'extract bed stdin',
               dnase_fwd_count_file, dnase_fwd_matrix_file, '-fill=0 -decimals=0 -tabs')
  try(system(cmd))

  cmd <- paste('cut -f 1-4', sites_file, '|', bwtool_path, 'extract bed stdin',
               dnase_rev_count_file, dnase_rev_matrix_file, '-fill=0 -decimals=0 -tabs')
  try(system(cmd))

  # Flip the counts generated from bwtool for motifs on the reverse strand
  rev_count_bwtool(sites_file, dnase_fwd_matrix_file, dnase_rev_matrix_file)

  cat('Combining DNase count matrices in both strands ...\n')

  dnase_fwd <- fread(dnase_fwd_matrix_file)
  dnase_rev <- fread(dnase_rev_matrix_file)

  dnase_combined <- cbind(dnase_fwd[,1:4],
                          dnase_fwd[,-c(1:4)],
                          dnase_rev[,-c(1:4)])

  dnase_counts <- list(fwd = dnase_fwd,
                       rev = dnase_rev,
                       combined = dnase_combined)
}

#' @title Flip the counts generated from bwtool for motifs on the reverse (minus) strand
#'
#' @param sites_file Filename for candidate sites
#' @param dnase_fwd_matrix_file Filename for DNase count matrix in forward strand
#' @param dnase_rev_matrix_file Filename for DNase count matrix in reverse strand
#' @importFrom  data.table fread fwrite
#' @export
#'
rev_count_bwtool <- function(sites_file, dnase_fwd_matrix_file, dnase_rev_matrix_file) {

  fwd_count.df <- fread(dnase_fwd_matrix_file)
  rev_count.df <- fread(dnase_rev_matrix_file)
  sites.df <- fread(sites_file)

  if(sum(sites.df[,2] != fwd_count.df[,2]) != 0) {
    stop('Sites do not match!')
  } else {
    # Extract the count values
    fwd_count.m <- as.matrix(fwd_count.df[, -c(1:5)])
    colnames(fwd_count.m) <- paste0('F', c(1:ncol(fwd_count.m)))
    rev_count.m <- as.matrix(rev_count.df[, -c(1:5)])
    colnames(rev_count.m) <- paste0('R', c(1:ncol(rev_count.m)))

    fwd_output <- fwd_count.m
    rev_output <- rev_count.m

    # For motifs match to the minus strand, flip the fwd and rev counts, and reverse the counts
    idx_minusStrand <- which(sites.df[,6] == '-')

    fwd_output[idx_minusStrand, ] <- t(apply(rev_count.m[idx_minusStrand, ], 1, rev))
    rev_output[idx_minusStrand, ] <- t(apply(fwd_count.m[idx_minusStrand, ], 1, rev))

    # Add the sites info to the first few columns
    fwd_count.df <- cbind(sites.df[,c(1:3,6)], fwd_output)
    rev_count.df <- cbind(sites.df[,c(1:3,6)], rev_output)

    fwrite(fwd_count.df, dnase_fwd_matrix_file, sep = ' ')
    fwrite(rev_count.df, dnase_rev_matrix_file, sep = ' ')

  }

}

