
#' @title Get total number of mapped reads from the idxstats file generated by samtools
#'
#' @param idxstats_file idxstats file generated by samtools.
#' @param select.chr Logitic. If TRUE (default), select chromosomes in chrs.
#' Otherwise, use all chromosomes in the idxstats file.
#' @param chrs Chromosomes to be included (default: paste0('chr', c(1:22)))
#'
#' @export
#'
get_total_reads <- function(idxstats_file, select.chr = TRUE, chrs = paste0('chr', c(1:22))) {
  count.df <- as.data.frame(data.table::fread(idxstats_file, sep = '\t'))
  names(count.df) <- c('chr', 'length', 'reads_mapped', 'reads_unmapped')

  if( select.chr ){
    total_count <- sum(count.df[which(count.df$chr %in% chrs), 'reads_mapped'])
  } else {
    total_count <- sum(count.df[, 'reads_mapped'])
  }

  return(total_count)
}


#' @title Sort and index the BAM file, and retrieve stats (idxstats)
#'
#' @param bam_file Input BAM file.
#' @param outdir Output directory.
#' @param sort Logical. If TRUE, sort (and index) the BAM file.
#' @param stats Logical. If TRUE, retrieve stats (idxstats) in the index file.
#' @param samtools_path Path to samtools executable.
#' @export
#'
bam_sort_index_stats <- function(bam_file,
                                 outdir,
                                 sort=TRUE,
                                 stats=TRUE,
                                 samtools_path='samtools') {

  if ( system( paste(samtools_path,'--help') , ignore.stdout=T,ignore.stderr=T ) != 0 ) {
    stop('ERROR: samtools could not be executed, set samtools_path!')
  }

  if( missing(outdir) ) {
    outdir <- dirname(bam_file)
  } else {
    dir.create(outdir, showWarnings = FALSE, recursive = TRUE)
  }

  bam_prefix <- gsub('.bam$', '', basename(bam_file))
  bam_file_sorted <- paste0(outdir, '/', bam_prefix, '.bam')

  if( sort ) {
    # sort and index the bam file
    cat('Sort and index the bam file...\n')
    bam_file_tmp <- paste0(outdir, '/', bam_prefix, '.tmp.bam')
    system( paste(samtools_path, 'sort', bam_file, '-o', bam_file_tmp) )

    file.rename(from = bam_file_tmp, to = bam_file_sorted)
    system( paste(samtools_path, 'index', bam_file_sorted) )
  }

  if( stats ){
    # Get index statistics (including the number of mapped reads in the third column)
    cat('Retrieve and print stats in the index file. Result saved to: ', bam_idxstats, '\n', sep='')
    bam_idxstats <- paste0(outdir, '/', bam_prefix, '.bam.idxstats.txt')
    system( paste(samtools_path, 'idxstats', bam_file_sorted, '>', bam_idxstats) )
  }

}
